name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::869935090803:user/honey:role/GitHubActionsS3Role
        aws-region: ap-southeast-2

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://dongheon-resume --exclude ".git/*" --acl public-read
